/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MatrixTest {
    @Test void appHasAGreeting() {
        assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
