/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest
{
    @Test void test1() {
        Integer result = StringCalculator.add("1,2,3,4");
        assertEquals(10, result);
    }
    @Test void test2() {
        Integer result = StringCalculator.add("1 2");
        assertEquals(-1, result);
    }
    @Test void test3() {
        Integer result = StringCalculator.add("1\n2");
        assertEquals(3, result);
    }
    @Test void test4() {
        Integer result = StringCalculator.add("");
        assertEquals(0, result);
    }
    @Test void test5() {
        Integer result = StringCalculator.add("1,2");
        assertEquals(3, result);
    }
    @Test void test6() {
        Integer result = StringCalculator.add("-1,2,1");
        assertEquals(2, result);
    }
    @Test void test7() {
        Integer result = StringCalculator.add("1,2,3");
        assertEquals(6, result);
    }
    @Test void test8() {
        Integer result = StringCalculator.add("1,\n");
        assertEquals(-1, result);
    }
    @Test void test9() {
        Integer result = StringCalculator.add("//;\n1,2\n3;4");
        assertEquals(10, result);
    }
    @Test void test10() {
        Integer result = StringCalculator.add("//;\n1,;");
        assertEquals(-1, result);
    }
    @Test void test11() {
        Integer result = StringCalculator.add("//!\n1!2");
        assertEquals(3, result);
    }
    @Test void test12() {
        Integer result = StringCalculator.add("//!\n1!-22");
        assertEquals(-1, result);
    }
    @Test void test13() {
        Integer result = StringCalculator.add("//!\n1!2200");
        assertEquals(1, result);
    }
    @Test void test14() {
        Integer result = StringCalculator.add("//[]\n1**2****3");
        assertEquals(6, result);
    }
}
