/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest
{
    @Test void test1() {
        Integer result = StringCalculator.add("1,2,3");
        assertEquals(-1, result);
    }
    @Test void test2() {
        Integer result = StringCalculator.add("1 2");
        assertEquals(-1, result);
    }
    @Test void test3() {
        Integer result = StringCalculator.add("1\n2");
        assertEquals(-1, result);
    }
    @Test void test4() {
        Integer result = StringCalculator.add("");
        assertEquals(0, result);
    }
    @Test void test5() {
        Integer result = StringCalculator.add("1,2");
        assertEquals(3, result);
    }
}
