/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;
import java.util.*;




public class StringCalculator
{
    public static int add(String numbers)
    {
        if(numbers.isEmpty())
        {
            return 0; 
        }
        String[] modified_numbers = get_numbers_string(numbers);

        int del = 1;
        for(String i: modified_numbers)
        {
            if(!(i.length() == 1))
            {
                del = 0;
            }
        }
        Integer result = sum(modified_numbers, del);
        return result;
    }

    private static String[] get_numbers_string(String numbers)
    {
        String delemiter = ",";
        if(numbers.endsWith("\n")||numbers.endsWith(delemiter))
        {
                numbers += "!";
                return numbers.split("\n");
        }

        List<String> custom_delemiters = new  ArrayList<String>(); 
        if(numbers.startsWith("//"))
        {
            String[] tokens = numbers.split("\n", 2);
            numbers = tokens[1];
            custom_delemiters = get_custom_delemiters(tokens[0]);
        }
        for(String i: custom_delemiters)
        {
            if (i == "")
            {
                return numbers.split("(?!^)");
            }
            if(numbers.endsWith(i))
            {
                numbers += "!";
                return numbers.split("\n");
            }
            numbers = numbers.replace(i, delemiter);

        }
        

        
        return numbers.replace("\n", delemiter).split(delemiter);

    }
    private static int sum(String[] modified_numbers, int del)
    {
        if (del == 1)
        {
            
            
            Integer sum_ = 0;
            for (String i: modified_numbers)
            {
                char ch = i.charAt(0);
                if (!Character.isDigit(ch))
                {
                    continue;
                }
                int char_ = ch - '0';
                sum_ += char_;
            }
            
            return sum_;
        }
        try
        {
            Integer sum = 0;
            Integer number = 0;
            List<Integer> integer_list = new ArrayList<Integer>();
            List<Integer> non_valid_integer = new ArrayList<Integer>();
            for (String i: modified_numbers)
            {
                number = Integer.valueOf(i);
                if (number < 0)
                {
                    non_valid_integer.add(number);
                    continue;
                }
                integer_list.add(number);
            }
            if (non_valid_integer.isEmpty())
            {
                for (Integer i:  integer_list)
                {
                    if( i > 1000)
                    {
                        continue;
                    }
                    sum += i;
                    System.out.println("Result : " + sum);
                    return sum;
                }
            }
            System.out.println("There is negative number(s):");
            for(Integer i: non_valid_integer)
            {
                System.out.println(i);
            }
            throw new NumberFormatException();      
        }
        catch (NumberFormatException ex)
        {
            ex.printStackTrace();
            return -1;
        }
    }

    private static List<String> get_custom_delemiters(String delemiters)
    {
        
        delemiters = delemiters.replace("//", "");
        delemiters = delemiters.replace("\n", "");
        delemiters = delemiters.replace("[", " ");
        delemiters = delemiters.replace("]", " ");
        
        List<String> dele = new ArrayList<String>();
        
        StringTokenizer st1 = new StringTokenizer(delemiters, " ");
        
        while (st1.hasMoreTokens())
            dele.add(st1.nextToken());
        return dele;
    }

    public static void main(String[] args) 
    {
       add("//!\n1!-22!-3");
    }
}
